package com.amazonaws.mobilehelper.auth.signin.ui.buttons;
//
// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-android v0.18
//

import android.app.Activity;
import android.content.Context;
import android.content.ContextWrapper;
import android.support.annotation.Nullable;
import android.support.v7.widget.AppCompatButton;
import android.util.AttributeSet;

import com.amazonaws.mobilehelper.auth.IdentityProviderType;
import com.amazonaws.mobilehelper.auth.signin.SignInManager;

/**
 * A Facebook button that will render appropriately for different sizes. By default, the button
 * will display showing an icon and text.  The button can be set to small style to show only
 * the icon.
 */
public class FacebookButton extends AppCompatButton {

    /**
     * Constructor.
     *
     * @param context context.
     */
    public FacebookButton(Context context) {
        this(context, null);
    }

    /**
     * Constructor.
     *
     * @param context context.
     * @param attrs   attribute set.
     */
    public FacebookButton(Context context, @Nullable AttributeSet attrs) {
        this(context, attrs, 0);
    }

    /**
     * Constructor
     *
     * @param context      context.
     * @param attrs        attribute set.
     * @param defStyleAttr default style attribute.
     */
    public FacebookButton(Context context, @Nullable AttributeSet attrs, int defStyleAttr) {
        super(context, attrs, defStyleAttr);
        final SignInManager signInManager = SignInManager.getInstance();
        if (getContext() instanceof Activity) {
            signInManager.initializeSignInButton((Activity) getContext(), IdentityProviderType.FACEBOOK, this);
        } else {
            ContextWrapper contextWrapper = (ContextWrapper) getContext();
            signInManager.initializeSignInButton((Activity) contextWrapper.getBaseContext(), IdentityProviderType.FACEBOOK, this);
        }
    }
}
