//
// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-android v0.18
//
package com.amazonaws.mobilehelper.util;

import android.app.Activity;
import android.app.AlertDialog;

/**
 * Utilities for Views.
 */
public final class ViewHelper {
    /**
     * Displays a modal dialog with an OK button.
     *
     * @param activity invoking activity
     * @param title    title to display for the dialog
     * @param body     content of the dialog
     */
    public static void showDialog(final Activity activity, final String title, final String body) {
        if (null == activity) {
            return;
        }

        final AlertDialog.Builder builder = new AlertDialog.Builder(activity);
        if (title != null && !title.isEmpty()) {
            builder.setTitle(title);
        }
        builder.setMessage(body);
        builder.setNeutralButton(android.R.string.ok, null);
        builder.show();
    }

}
